### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [joyfulmantis/joyfulmantis.github.io-src#1]
I would like to be able to follow an Atom or RSS feed of your posts. Hakyll supports this out of the box: https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html

**Comment by joyfulmantis** [comment]
Thanks for you input. I have added an atom feed at http://joyfulmantis.github.io/atom.xml . Please let me know if there are any more issues!

**Comment by tfausak** [comment]
Great, thanks!
